name:                arduino-lights
version:             0.1.0.0
github:              "mitchellvitez/arduino-lights"
author:              "Mitchell Vitez"
maintainer:          "mitchell@vitez.me"
copyright:           "2021 Mitchell Vitez"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mitchellvitez/arduino-lights#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  arduino-lights-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
